#!/bin/bash
# vim: set ft=sh

set -e -x

FIRST_GOPATH=`echo $GOPATH | cut -d':' -f1`

source_root=$PWD

pushd $FIRST_GOPATH
  git clone https://github.com/cloudfoundry-incubator/diego-workspace
  cp ./diego-workspace/Cartridge.lock $source_root
popd

mkdir -p $FIRST_GOPATH/bin
export PATH=$FIRST_GOPATH/bin:$PATH

go get -v github.com/vito/gocart

gocart
go install github.com/onsi/ginkgo/ginkgo

ginkgo -r -i -skipMeasurements -randomizeAllSpecs "$@"
