#!/bin/bash
# vim: set ft=sh

set -e -x

FIRST_GOPATH=`echo $GOPATH | cut -d':' -f1`

mkdir -p $FIRST_GOPATH/bin
export PATH=$FIRST_GOPATH/bin:$PATH

go get -v github.com/vito/gocart

for gopath in `echo $GOPATH | cut -d':' -f1`; do
  find $gopath
done

gocart
go install github.com/onsi/ginkgo/ginkgo

git status
git diff Cartridge.lock
cat Cartridge.lock

ginkgo -r -i -skipMeasurements -randomizeAllSpecs "$@"
